In [27]:
alist = [1,2,3]
arr = np.array(alist)

#criando array de 'zeros' tendo n elementos
array1 = np.zeros(5)
array1

#Criando um array obedecendo um range
array2 = np.arange(100)
array2

#de 10 a 100
array3 = np.arange(10, 100)
array3

#200 passos entre 0 e 1
array4 = np.linspace(0,1, 200)
array4

array([0.        , 0.00502513, 0.01005025, 0.01507538, 0.0201005 ,
       0.02512563, 0.03015075, 0.03517588, 0.04020101, 0.04522613,
       0.05025126, 0.05527638, 0.06030151, 0.06532663, 0.07035176,
       0.07537688, 0.08040201, 0.08542714, 0.09045226, 0.09547739,
       0.10050251, 0.10552764, 0.11055276, 0.11557789, 0.12060302,
       0.12562814, 0.13065327, 0.13567839, 0.14070352, 0.14572864,
       0.15075377, 0.15577889, 0.16080402, 0.16582915, 0.17085427,
       0.1758794 , 0.18090452, 0.18592965, 0.19095477, 0.1959799 ,
       0.20100503, 0.20603015, 0.21105528, 0.2160804 , 0.22110553,
       0.22613065, 0.23115578, 0.2361809 , 0.24120603, 0.24623116,
       0.25125628, 0.25628141, 0.26130653, 0.26633166, 0.27135678,
       0.27638191, 0.28140704, 0.28643216, 0.29145729, 0.29648241,
       0.30150754, 0.30653266, 0.31155779, 0.31658291, 0.32160804,
       0.32663317, 0.33165829, 0.33668342, 0.34170854, 0.34673367,
       0.35175879, 0.35678392, 0.36180905, 0.36683417, 0.37185

In [49]:
#criar uma matriz 5x5
image = np.zeros((5,5))
image

#criar um cubo 5x5x5
cube = np.zeros((5,5,5)).astype(int)+1
cube

cube2 = np.ones((5,5,5)).astype(np.float16)
cube2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [52]:
#array de zeros do tipo inteiro
arr = np.zeros(2, dtype = int)
arr[0] = 5.98454654315
arr

#array de zeros do tipo float
arr1 = np.zeros(2, dtype=np.float32)
arr1[0] = 5.98454654315
arr1

array([5.9845467, 0.       ], dtype=float32)

In [55]:
#modelando um array 3D de 5x5x5
arr1d = np.arange(125)
arr3d = arr1d.reshape((5,5,5))
arr3d

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [60]:
#"achatando" matrizes
arr5d = np.arange(1000)
arr4d = np.zeros((10,10,10,10))
arr5d = arr4d.ravel()
arr5d

array([0., 0., 0., ..., 0., 0., 0.])

In [67]:
#criando um vetor de zeros e definindo tipos de coluna
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
recarr

#definindo valores para adcionar ao array
toad = [(1,2., 'hello'), (2,3.,'world')]
recarr[:] = toad
recarr

array([(1, 2., b'hello'), (2, 3., b'world')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [72]:
recarr2 = np.zeros((4,), dtype=('i4,f4,a10'))

col1 = np.arange(4)+1
col2 = np.arange(4, dtype=np.float32)
col3 = ['Hello', 'World', 'my', 'friend']

toadd = zip(col1,col2,col3)

recarr2[:] = list(toadd)
recarr2

array([(1, 0., b'Hello'), (2, 1., b'World'), (3, 2., b'my'),
       (4, 3., b'friend')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [78]:
#chamando uma coluna pelo titulo
recarr.dtype.names = ('Integers', 'Floats', 'Strings')

recarr['Strings']



array([b'hello', b'world'], dtype='|S10')

In [80]:
#buscando elementos em python
novaLista = [[1,2],[3,4]]
novaLista[0][1]


2

In [87]:
arr = np.array(novaLista)
arr[0, 1]

arr[:,1]

arr[1,:]

array([3, 4])

In [94]:
arr11 = np.array([0,3,8,3])

index = np.where(arr11>2)
print(index)

new_arr = arr11[index]
print(new_arr)

(array([1, 2, 3], dtype=int32),)
[3 8 3]


In [95]:
new_arr2 = np.delete(arr11, index)
print(new_arr2)

[0]
